import './globals.css'
import { Inter } from 'next/font/google'
import { cn } from '@/utils/classNames'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'hostshare',
  description: 'Generated by create next app',
  icons: {
    icon: '/brand/logo-simple.png',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={cn(inter.className, 'antialiased')}>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
